### ISSUE TITLE
can't find source for forms in 'antisymmetric'

### ISSUE THREAD

**Issue by emckean** [tatuylonen/wiktextract#365] opened 2023-10-17 04:12 UTC
I'm trying to figure out where the 'forms' are coming from in the JSON for ['antisymmetric'](https://kaikki.org/dictionary/English/meaning/a/an/antisymmetric.html#antisymmetric-en-adj-D-8NsEsh)
`"forms": [
    {
      "form": "T_S≡1",
      "head_nr": 2,
      "tags": [
        "canonical",
        "error-unknown-tag"
      ]
    },
    {
      "form": "2",
      "head_nr": 2,
      "tags": [
        "canonical",
        "error-unknown-tag"
      ]
    },
    {
      "form": "T_A≡1",
      "head_nr": 2,
      "roman": "T-Tᵀ",
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "2",
      "head_nr": 2,
      "roman": "T-Tᵀ",
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "3.47",
      "head_nr": 2,
      "tags": [
        "romanization"
      ]
    },
    {
      "form": "are the symmetric and parts",
      "head_nr": 3,
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "respectively",
      "head_nr": 3,
      "tags": [
        "canonical"
      ]
    },
    {
      "form": "they are known as the of T.}}",
      "head_nr": 3,
      "tags": [
        "canonical"
      ]
    }
  ],`

Any ideas? I can't find anything in the pre-processed JSON or the [Wiktionary entry itself](https://en.wiktionary.org/wiki/antisymmetric).

**Comment by kristian-clausal** [comment] 2023-10-17 05:03
The <math> block in `## {{lb|en|of a [[tensor]]}} That changes sign when any two [[index|indices]] are interchanged (e.g., ''T<sub>ijk</sub>'' = -''T<sub>jik</sub>'');
##* {{quote-book|en|year=1986|author=Millard F. Beatty Jr.|title=Principles of Engineering Mechanics, Volume 1: Kinematics - The Geometry of Motion|publisher=Plenum Press|pageurl=https://books.google.com.au/books?id=q6lmnT1M86YC&pg=PA163&dq=%22antisymmetric%22&hl=en&sa=X&ved=0ahUKEwibup-ku9zbAhVlMn0KHYaGAXsQ6AEIPjAE#v=onepage&q=%22antisymmetric%22&f=false|page=163
|passage=Notice that the tensors defined by:<br>&nbsp;&nbsp;&nbsp;&nbsp;<math>\textstyle T_S\equiv\frac{1}{2}(T+T^T)</math>,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<math>\textstyle T_A\equiv\frac{1}{2}(T-T^T),</math>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3.47)<br>are the symmetric and '''antisymmetric''' parts, respectively; they are known as the ''symmetric and '''antisymmetric''' parts'' of T.}}` is probably being shunted to a new line by the `<br>` tag inside the template argument, and then the TS=== stuff is being parsed as a new head... The ½ after TS=== is trans...litterated as `1/2`, the / separates the TS===1 from the 2, the TA===1 from its 2, the T-TT is interpreted as a romanization because its in parentheses after the "form"...

This is an edgecase in a soup of edgecases, an edgecase's edgecase, the kind of edgecase other edgecases go to when they want to relax from being edgecases and just have a laugh. Fixing this is liable to break other things, I am elbow deep in old commits trying to nail down some memory-related bugs with Lua and multiprocessing, so unless @xxyzz wants to take a swing at this it'll be on the backburner for a while, and it might not be "fixable".

The issue is that our parser is just fundamentally different (with different priorities) than wikitext parsing usually; we do things in a slightly different order, which causes things to break and which then need to be fixed with different kludges, but it's all necessary because parsing wikitext to try to read it is so different from parsing wikitext to create a DOM.

A kludge for this could be to just remove / substitute newline-generating elements or characters (`\n` or `<br />`) with whitespace if they're inside templates... Except that would totally break all tables, which rely on newlines, and other stuff, including hieroglyphics. Damned if you do, damned if you don't.

**Comment by xxyzz** [comment] 2023-10-17 05:51
I think it the tex syntax `\frac{1}{2}` inside the `math` tag breaks the template node. I'll try to read the parser code to see how this could be fixed.

In situation like this, I just hope we could somehow use parsoid's parser and never need to deal with the regex parser...

**Closed** 2023-10-17 08:00 UTC

**Comment by emckean** [comment] 2023-10-17 14:05
Thank you! Totally understand, thank you so much for this amazing project!
