### ISSUE TITLE
errors in hyponym extraction when there are multiple senses

### ISSUE THREAD

**Issue by yuchenlin** [tatuylonen/wiktextract#21] opened 2020-05-29 02:00 UTC
Hi,

I just found there were some errors in `hyponyms` of `senses`. For example, the first entry about the word "dictionary", whose page is https://en.wiktionary.org/wiki/dictionary 

We can see that only the last sense is associated with "Hyponym: hash table", but in the processed results, all senses have this `hyponyms` in the `senses`. 

`
{"word": "dictionary", "senses": [{"glosses": ["A reference work with a list of words from one or more languages, normally ordered alphabetically, explaining each word's meaning, and sometimes containing information on its etymology, pronunciation, usage, translations, and other data."], "hyponyms": [{"word": "hash table"}]}, {"glosses": ["(preceded by the) A synchronic dictionary of a standardised language held to only contain words that are properly part of the language."], "tags": ["preceded by the"], "hyponyms": [{"word": "hash table"}]}, {"glosses": ["(by extension) Any work that has a list of material organized alphabetically; e.g., biographical dictionary, encyclopedic dictionary."], "tags": ["by extension"], "hyponyms": [{"word": "hash table"}]}, {"glosses": ["(computing) An associative array, a data structure where each value is referenced by a particular key, analogous to words and definitions in a physical dictionary."], "tags": ["computing"], "hyponyms": [{"word": "hash table"}]}], "pos": "noun"}
`

Thanks!

**Comment by yolpsoftware** [comment] 2020-05-29 07:48
The same problem exists with the examples, where I solved it with #17. Can you try out if #17 solves this problem as well?

**Comment by yuchenlin** [comment] 2020-05-29 07:52
@yolpsoftware Thank you very much! Will re-run the script with your version and have a look!

**Comment by yuchenlin** [comment] 2020-06-05 04:35
@yolpsoftware  Hi, I re-run the script with your forked version and it seems that the bug is still there.

**Comment by tatuylonen** [comment] 2020-12-15 20:18
The new version should now handle this.  However, I noticed some bugs when testing today (which are now fixed).  The HTML version at https://kaikki.org/dictionary/ should update in about 24 hours to reflect the changes.

**Comment by tatuylonen** [comment] 2020-12-18 14:48
Status update: the hyponym now seems to be correctly extracted and is included in the downloaded data, but is still not correctly displayed on the web site...  Turns out there was a bug in the script that generated the web site that caused all sense-disambiguated linkages to not be shown.  I fixed the bug and the hyponym should appear on the web site next time the web site updates during the weekend.

**Comment by tatuylonen** [comment] 2020-12-28 13:01
Confirmed that "hash table" is now correctly shown as hyponym for "dictionary" on the web site.

**Closed by tatuylonen** 2020-12-28 13:01 UTC

**Comment by yuchenlin** [comment] 2020-12-29 23:53
thanks a lot
