### ISSUE TITLE
Erroneous "class" in Swahili translations of English words

### ISSUE THREAD

**Issue by ChristianSi** [tatuylonen/wiktextract#199] opened 2023-01-06 12:11 UTC
I've noticed that since a few weeks, the word "class" appears in the Swahili translations of many English words, e.g. [airplane](https://kaikki.org/dictionary/All%20languages%20combined/meaning/a/ai/airplane.html) ("eropleni class"), [animal](https://kaikki.org/dictionary/All%20languages%20combined/meaning/a/an/animal.html) ("mnyama class"), and [baby](https://kaikki.org/dictionary/All%20languages%20combined/meaning/b/ba/baby.html). But actually this word is part of the metadata (the Swahili word class) and shouldn't appear as part of the translation itself.

Overall, more than 600 entries seem to be affected.

**Comment by kristian-clausal** [comment] 2023-01-09 06:46
Is this a change that happened since a few weeks ago, or is this something that you've only noticed now? Please be mindful of this distinction, so we don't end up going down a rabbit hole trying to figure out what could have changed...

This just seems that we didn't have enough variants of tag-mappings, as it always seems to be, so it's an issue that's been probably around forever. Fixed by copy-pasting a bunch of "9/10" style mappings in xlat_head_map and adding "class " in front of the duplicates so that we have both "class 9/10" and "9/10". We already had "class 9/10" (etc) in xlat_tags_map, but apparently that didn't catch in this case.

It is part of the ingenuity of wiktionary editors that they can always come up with a variant of something we're trying to parse that we haven't gotten in our data yet.

**Comment by kristian-clausal** [comment] 2023-01-09 07:41
I went back to checking old data, and an August 2020 wiktextract dump has the correct data (no "eropleni class"), so you are correct that there was a change.

Argh! Reopening to see if I can figure out what I did wrong...

**Comment by kristian-clausal** [comment] 2023-01-09 08:16
Closing this again. As long as we can fix any fallout like we did with "class 9/10", this is only an issue of updating our tag mappings when encountering new errors. In other words, it's not a bug, it's a *realignment of procedures with some minor side effects to be corrected as they become relevant*.

**Comment by ChristianSi** [comment] 2023-01-11 10:10
In the latest dump, the situation has much improved, but it's far from perfect. About 2/3 of the spurious "class" entries are fixed, but 1/3 remains. Some random example: Kijerumaniki class, Kutoka class, maandiko class, mapishi class, Mathayo class, Mfaransa class m-wa, Mika class, muziki class, mwendo class m/mi, Nehemia class, nyukliasi class, rafiki class, sanduku class, utumwa class, Uzeri class.

So I suggest you re-open this, @kristian-clausal  (since it seems I cannot). It's much better now, but there's still room for improvement!

**Comment by kristian-clausal** [comment] 2023-01-11 10:18
This is just a problem for collecting the tags needed for this so that we can add them explicitly to xlat_head_map. I just copypasted a block of "class XX" numbered stuff into xlat_head_map, which should fix some of the issues. Later, if you can collect the data, please add it here. I need to know what the *original text* on the wiktionary article looked like. For example for "utumwa" I had to first find where that was (in the English article translations for 'slavery', not the article 'utumwa'), and there I saw that it was **"class 11"**, which is the bit that is needed for xlat_head_map.

**Comment by kristian-clausal** [comment] 2023-01-12 07:09
Forgot to commit and push, should see results tomorrow.

**Comment by ChristianSi** [comment] 2023-01-12 10:41
@kristian-clausal:

> I need to know what the *original text* on the wiktionary article looked like.

Well, I don't have that information either, since I only work with the data from your dump, not with the raw Wikipedia data itself. What I *could* give you is the English word for which the translation is listed, including its word class and the sense under which the translation is listed.

For example, "rafiki class" is from "comrade" (noun), senses "fellow socialist or communist" and "mate, companion, or associate". Not sure if that information would help?

> Forgot to commit and push, should see results tomorrow.

I don't know what you changed now, but if I see changes in regard to this issue in a future dump, I'll report back.

**Comment by ChristianSi** [comment] 2023-01-17 15:35
In the latest dump, the situation with the spurious "class" entries has again much improved. Thanks!

However, I still found that word in the entries listed in the attached file. Explanations:

* class: the word class (POS tag)
* sense: the sense under which translations are grouped
* en: the English word
* sw: the Swahili translation

Hope this helps!

[sw-class.txt](https://github.com/tatuylonen/wiktextract/files/10436595/sw-class.txt)

**Comment by kristian-clausal** [comment] 2023-01-19 06:39
To get the information about what the original text is, you can just look at the original wikitext, especially the ones that end with just "class" because those are ones that are cut off. Stuff like "class m/mi" happens to be the same as the original text without being cut off, because we don't have "class m/mi" or "m/mi" in our data, just "class m-mi" and "m-mi".

In other news, I found *yet another* place in our code where you can put stuff to be mapped... Specifically, head_final_bantu_map... That is what was causing the cut-off for "class u" and "class n", it would parse the "u" separately because head_final_bantu_map didn't have "class u", and so the u would be separated and discarded when parsing the rest. I've now filled up the list with a bunch of variations.

... I just came across "class IX/X" in the list. God dammit. Just... How many ways can wiktionary inventors find to say the same thing? Well, on the list it goes. Expect a commit in an hour or two, I'm just going through the list by hand.

**Comment by kristian-clausal** [comment] 2023-02-15 12:37
I checked our data and could only find on new example of "class" in a Swahili translation of an English word, and added that one.

That should be the last of the explicit ones using the word "class" for now. I'm going to close this issue and then some day in the future a new issue can be opened up when people have figured out new ways to do this formatting.

**Closed by kristian-clausal** 2023-02-15 12:37 UTC

**Comment by ChristianSi** [comment] 2023-02-15 14:25
Yeah, that good very good now! I too could fine one one example which still has *class*: *bima class 9/c10* as translation of **insurance**. Maybe that's the one you just fixed?
