### ISSUE TITLE
Missing sense for "cavolo"

### ISSUE THREAD

**Issue by seth-js** [tatuylonen/wiktextract#142] opened 2022-08-03 21:47 UTC
I downloaded the non-inflected, non-alternative word senses JSON for Italian, and I noticed that cavolo is missing one of its definitions. 

It's visible [on the site](https://kaikki.org/dictionary/Italian/meaning/c/ca/cavolo.html#cavolo-it-noun-07DE1.4z), but missing in the JSON.

**Comment by kristian-clausal** [comment] 2022-08-05 05:48
It's easy to miss, but "cabbage" is present inside "senses".

```
  "senses": [        #List
    {     # entry 1
      "glosses": [
        "cabbage"
      ],
      "raw_glosses": [
        "cabbage"
      ],
      "tags": [
        "masculine"
      ]
    },
    {   # entry 2
      "categories": [
        "Italian euphemisms",
        "Italian terms with usage examples"
      ],
      "examples": [
        {
          "english": "what the fuck are you doing?",
          "text": "che cavolo fai?",
          "type": "example"
        }
      ],
      "form_of": [
        {
          "extra": "the fuck, the hell",
          "word": "cazzo"
        }
      ],
      "glosses": [   # gloss 2
        "Euphemistic form of cazzo; the fuck, the hell"
      ],
      "raw_glosses": [
        "(intensifier) Euphemistic form of cazzo; the fuck, the hell"
      ],
      "synonyms": [
        {
          "word": "diavolo"
        },
        {
          "word": "cacchio"
        },
        {
          "alt": "vulgar",
          "word": "cazzo"
        }
      ],
      "tags": [
        "emphatic",
        "euphemistic",
        "form-of",
        "intensifier",
        "masculine"
      ]
    }
  ],
```

The dictionaries are pretty-printed in alphabetical order, so when there are many qualifiers in an entry the "head"-entry (in this case "gloss") can be  a bit hidden.

The pretty-printer could be improved, maybe with color-coding and bigger indentation. At the moment I think it just uses the raw output of python's JSON pretty-printer, so it would be a project in itself, and would create strain on the HTML-generator which has had some problems lately with memory thanks to us creating new pages to generate.

**Comment by seth-js** [comment] 2022-08-05 06:19
I'm not seeing the euphemism entry in the JSON at all.

```
{
  "pos": "noun",
  "head_templates": [
    {
      "name": "it-noun",
      "args": { "1": "m" },
      "expansion": "cavolo m (plural cavoli)"
    }
  ],
  "forms": [{ "form": "cavoli", "tags": ["plural"] }],
  "etymology_text": "From Late Latin caulus, from Latin caulis, or from Ancient Greek \u03ba\u03b1\u03c5\u03bb\u03cc\u03c2 (kaul\u00f3s). Compare Sicilian cavulu.",
  "etymology_templates": [
    {
      "name": "inh",
      "args": { "1": "it", "2": "LL.", "3": "caulus" },
      "expansion": "Late Latin caulus"
    },
    {
      "name": "inh",
      "args": { "1": "it", "2": "la", "3": "caulis" },
      "expansion": "Latin caulis"
    },
    {
      "name": "der",
      "args": {
        "1": "it",
        "2": "grc",
        "3": "\u03ba\u03b1\u03c5\u03bb\u03cc\u03c2"
      },
      "expansion": "Ancient Greek \u03ba\u03b1\u03c5\u03bb\u03cc\u03c2 (kaul\u00f3s)"
    },
    {
      "name": "cog",
      "args": { "1": "scn", "2": "cavulu" },
      "expansion": "Sicilian cavulu"
    }
  ],
  "sounds": [{ "ipa": "/\u02c8ka.vo.lo/" }, { "rhymes": "-avolo" }],
  "word": "cavolo",
  "lang": "Italian",
  "lang_code": "it",
  "related": [
    { "word": "cavolaia", "_dis1": "0 0" },
    { "word": "cavolaio", "_dis1": "0 0" },
    { "word": "cavolata", "_dis1": "0 0" },
    { "word": "cavoletto", "_dis1": "0 0" },
    { "word": "cavolfiore", "_dis1": "0 0" },
    { "word": "cavolino", "_dis1": "0 0" },
    { "word": "cavolino di Bruxelles", "_dis1": "0 0" },
    { "word": "cavolo cappuccio", "_dis1": "0 0" },
    { "word": "cavolo cinese", "_dis1": "0 0" },
    { "word": "cavolo di Bruxelles", "_dis1": "0 0" },
    { "word": "cavolo nero", "_dis1": "0 0" },
    { "word": "cavolo rapa", "_dis1": "0 0" },
    { "word": "cavolo riccio", "_dis1": "0 0" },
    { "word": "cavolo riscaldato", "_dis1": "0 0" },
    { "word": "cavolo rosso", "_dis1": "0 0" },
    { "word": "incavolarsi", "_dis1": "0 0" },
    { "word": "verza", "_dis1": "0 0" }
  ],
  "senses": [
    {
      "raw_glosses": ["cabbage"],
      "tags": ["masculine"],
      "glosses": ["cabbage"],
      "id": "cavolo-it-noun-Cnonvt0f",
      "categories": [
        {
          "name": "Brassicas",
          "kind": "lifeform",
          "parents": [
            "Crucifers",
            "List of sets",
            "Brassicales order plants",
            "All sets",
            "Plants",
            "Fundamental",
            "Lifeforms",
            "Nature",
            "All topics"
          ],
          "source": "w+disamb",
          "orig": "it:Brassicas",
          "langcode": "it",
          "_dis": "87 13"
        },
        {
          "name": "Vegetables",
          "kind": "lifeform",
          "parents": [
            "Foods",
            "List of sets",
            "Plants",
            "Food and drink",
            "All sets",
            "Lifeforms",
            "All topics",
            "Fundamental",
            "Nature"
          ],
          "source": "w+disamb",
          "orig": "it:Vegetables",
          "langcode": "it",
          "_dis": "71 29"
        }
      ]
    }
  ]
}

```
I downloaded the JSON from [here](https://kaikki.org/dictionary/Italian/nonsenses.html), but now I'm assuming that's the wrong place.

**Comment by kristian-clausal** [comment] 2022-08-05 07:31
You've stumbled into something that I'm not actually sure what it is yet. I am guessing "non-inflected" and "non-alternative" are meant for basic words and basic word forms. You're correct that the json file dump of "all the words" https://kaikki.org/dictionary/Italian/all-non-inflected-senses/kaikki.org-dictionary-Italian-all-n-CwCF2E does not seem to contain the entry for euphemistic "cavolo".

I am pretty sure this is half by design: euphemistic "cavolo" is tagged as a "form-of", which is used for inflected forms (and apparently euphemisms, too), so it's an **inflected/alternative** form. According to this tag, it shouldn't appear (correctly) in the json data, but it *does* appear (incorrectly) in the index https://kaikki.org/dictionary/Italian/all-non-inflected-senses-cavea--cazzuto.html as a link.

This seems just that it's a bug in the code that generates these links. It probably creates as many links as it needs for each sense that it can find https://kaikki.org/dictionary/Italian/meaning/c/ca/cavolo.html without taking into account the "non-alternative" and "non-inflected" part above, so the list of word sense contains false positives that are not present in the json-data.

I'll try to take a look at it, but this seems like a low priority issue at the moment, and might be too much of a nut to crack for me. A third solution would be for the form-of tag not to be applied in situation likes this, but it's a bit borderline.

**Comment by seth-js** [comment] 2022-08-05 07:47
It's no problem. It's not that big a deal since I can just download the all word forms JSON and work with the data provided from there. Thank you for helping me out.

**Comment by kristian-clausal** [comment] 2022-08-05 07:52
Excellent if it's not a big stumbling block. I'll be closing this, but feel free to open a new issue if something else pops up.

**Closed by kristian-clausal** 2022-08-05 07:52 UTC
Labels: enhancement
