### ISSUE TITLE
Missing Polish declensions

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#169] opened 2022-10-19 19:40 UTC
For example for the word https://en.wiktionary.org/wiki/%C5%BC%C3%B3%C5%82wik has declensions on Wiktionary, but they don't seem to exist in the kaikki data. Another example would be https://en.wiktionary.org/wiki/%C5%82ysk .

**Comment by kristian-clausal** [comment] 2022-10-20 05:04
Hopefully this is straightforward. Seems the problem is in
```{{safesubst:<noinclude/>#invoke:pl-noun|template_decl_pattern|m-in}}<noinclude>{{documentation}}</noinclude>```
which is then expanded into 
```<strong class="error">Template:&lt;noinclude/&gt;#invoke:pl-noun</strong>```

It's our friend `<noinclude\>` again. Because wikitextprocessor and wiktextract only *emulate* the behavior of the background parsers in Wikistuff, it's really easy for edge cases like the above to get through. The html-escaped lt and gt are probably not the cause (because you would see those if they did slip through), I bet it's because the `<noinclude/>` has been yet again crammed into an awkward position. Time to ping @tatuylonen

**Comment by kristian-clausal** [comment] 2022-10-20 12:05
Fixed with 25b0f1a87a5b42ae5e70608a14c4a0ac6b2b9693 in wikitextprocessor.

`<noinclude/>` was getting through into tname, template-name/first argument, so as a fix I used a simple regex to strip it away before it was being used and was going through some string-manipulation stuff already. This seemed to fix the issue with Polish tables, although it brought up a few missing-`</span>` error messages and a novel `tracking/headword/pagename spelling mismatch/pl` that I have not come across before. That "pl" is obviously from pl-noun or something else, but... I'll leave that for another issue.

**Closed by kristian-clausal** 2022-10-20 12:05 UTC
Labels: bug, wiktionary template
