### ISSUE TITLE
raw glosses truncated for Spanish entries in enwiktionary dump

### ISSUE THREAD

**Issue by jhammen** [tatuylonen/wiktextract#771] opened 2024-08-14 13:26 UTC
I am working with the Spanish entries from enwiktionary, the file I have is kaikki.org-dictionary-Spanish.jsonl, it was created 2024-08-12

The data looks great in general, the issue I am having is with some entries where the raw glosses seem to be truncated, I see this in certain verb forms.

An example: the word "alcance" a form of "alcanzar", here are the glosses and raw glosses, it looks like the raw version is cut off:

```
"raw_glosses": [
        "inflection of alcanzar:\n"
      ],
"glosses": [
        "inflection of alcanzar:\n## first/third-person singular present subjunctive\n## third-person singular imperative",
        "third-person singular imperative"
      ]
```

I thank you for your attention to this issue and also for providing such useful data.

**Comment by kristian-clausal** [comment] 2024-08-15 06:14
I've been poking around in the glosses code, so I guess it's time to figure out whether this is a regression, a new bug by me, or something old.

**Comment by kristian-clausal** [comment] 2024-08-15 06:40
This seems like an old issue, but I have a vague recollection of this, or something similar (maybe pronunciation section templates) being fixed.

In any case, it's caused by how the `Template:es-verb form of` template just dumps a whole sublist into the gloss without as much as a howdydo. The whole thing gets expanded too late and parsed as a single gloss, and all the systems in place trying to figure out subglosses in different ways have failed. I'll see what I can do.

**Comment by kristian-clausal** [comment] 2024-08-15 08:58
Should be fixed with this, if you find anything else please go ahead and make a new issue, if this doesn't seem to be fixed just post here and I'll reopen.

**Closed** 2024-08-15 08:57 UTC
