### ISSUE TITLE
How to see the translated words in other languages?

### ISSUE THREAD

**Issue by RuoniWang** [tatuylonen/wiktextract#19] opened 2020-05-22 23:52 UTC
While translations in French etc. that also use a-z letters show up correctly, translations in other languages mostly show up as something like "\u03c3\u03c5\u03bd\u03b5\u03ba\u03b4\u03bf\u03c7\u03ae", wonder how I can get them to show up correctly?

**Comment by yolpsoftware** [comment] 2020-05-24 18:39
Maybe a duplicate of https://github.com/tatuylonen/wiktextract/pull/18

**Comment by tatuylonen** [comment] 2020-12-15 19:20
In the current version, translations are stored under "translations" key in the word sense (if they have been disambiguated to a word sense) or under the word if they have not been disambiguated to a word sense.  The disambiguation is currently *very* basic.  But basically you need to check both places.  You can easily explore the data at [https://kaikki.org/dictionary/](https://kaikki.org/dictionary/).

**Closed by tatuylonen** 2020-12-15 19:20 UTC
