### ISSUE TITLE
Unable to find all parts of speech for words

### ISSUE THREAD

**Issue by meetDeveloper** [tatuylonen/wiktextract#116] opened 2022-02-12 04:18 UTC
I was browsing https://kaikki.org/dictionary/English/meaning/h/he/hello.html and I noticed we only have Interjection present whereas in Wiktionary https://en.wiktionary.org/wiki/hello we have noun and verb also present. Can you look into this? Thank you.

**Comment by tatuylonen** [comment] 2022-02-20 23:05
Sorry I've been working mostly on other things for the last couple of weeks.  This seems to be an error in wikitextprocessor, which incorrectly expands the translation "{{tt+|fr|!}}" for French under "is anyone there?".  The problem disappears if I remove the trans-top or multitrans templates, so something to do with template nesting.  I'm still working to find the root cause.  I'm still working to actually fix it.  (I've also been hunting down another issue in wikitextprocessor recently, and there is some possibility these are connected.)

**Comment by meetDeveloper** [comment] 2022-03-06 04:36
Found another example but this one looks little different not sure if the cause would be same or not.
For word real we have in Etymology 3, noun as parts of speech under which we have two different type of noun senses.

Unable to find following part of speech in dictionary [here](https://kaikki.org/dictionary/English/meaning/r/re/real.json).

real (plural reais or reals)      
1. A unit of currency used in Brazil since 1994. Symbol: R$.       
2. A coin worth one real.

![image](https://user-images.githubusercontent.com/32453612/156909371-ac181a43-161d-4054-ab60-d06c014855fb.png)

**Comment by meetDeveloper** [comment] 2022-09-24 12:46
@tatuylonen @kristian-clausal Is there any progress regarding this?

**Comment by kristian-clausal** [comment] 2022-09-28 06:04
@meetDeveloper Sorry, no. There's a bunch of fires going on elsewhere that Tatu is trying to figure out (issues that come up at the kaikki.org scale, so it's slow going), and I'm not qualified to look at this particular issue yet. It's on the list, it's a bug, but it's not at the top because template-parsing and nesting might have something to do with Lua, and we have a lot of issues with Lua in particular.

**Comment by kristian-clausal** [comment] 2022-10-17 07:01
Looking at the specific examples, the translation templates in the French section are borked because of an automated script 'bug' in https://en.wiktionary.org/w/index.php?title=hello&diff=54532137&oldid=54531846 which I don't even want to call a bug because it's a simple case of garbage-in-garbage-out.

```* French: {{t|fr|eh oh}}&nbsp;?, {{t|fr|oh eh}}&nbsp;?, {{t+|fr|allô}}&nbsp;?, {{t+|fr|ohé}}&nbsp;!``` -->
```* French: {{t|fr|eh oh}}, {{t|fr|?}}, {{t|fr|oh eh}}, {{t|fr|?}}, {{t|fr|allô}}, {{t|fr|?}}, {{t|fr|ohé}}, {{t|fr|!}}```

Obviously this needs to be corrected on wiktionary's side. This issue might or might not be duplicated, I'll try to see if I can find other examples of it in the dump. If the issue is that a single "!" breaks the template expansion (wouldn't be strange, currently we're handling stuff like {{!}} as a special case), then the fix might be just to find all the examples of the above kind of bot-script artifact and fix them on Wiktionary.

**Comment by kristian-clausal** [comment] 2022-10-17 07:42
Separated the real-related post to its own issue.

**Comment by kristian-clausal** [comment] 2022-11-29 11:15
This seems like the original issue is now handled (at least "hello" is parsed correctly) and the reais-issue was separated (and then closed) in its own thread, so closing this.

**Closed by kristian-clausal** 2022-11-29 11:16 UTC
Labels: bug, wiktionary template
