### ISSUE TITLE
Missing form_of keys for some senses

### ISSUE THREAD

**Issue by Vuizur** [tatuylonen/wiktextract#514] opened 2024-02-23 09:53 UTC
A few senses are missing the form_of key. 
I made a heuristic check and searched for glosses containing the word "singular", but where there was no form_of or alt_of key in the sense:
The results are as follows:
lang_code  |count|
-----------|----|
la         |99302|
it         |39869|
fr         |13659|
ru         |13499|
es         | 9778|
pl         | 6413|
de         | 6282|
nl         | 3905|
hu         | 3756|
gl         | 3307|
hi         | 2878|
sh         | 2501|

A few are false positives, but for languages like Italian and French it is a somewhat widespread occurance. 
Example words: 
Italian: ami, tuba, impala, copula, replica, musica, pesca.
French: cube, abuse, azure, update, love
Latin: multi, maximum, visa, gemini
Russian: используешь, удачи, малого, змея

Thanks a lot for all the recent commits!

**Comment by kristian-clausal** [comment] 2024-02-23 10:24
```
Verb

ami

    inflection of amare:
        second-person singular present indicative
        first/second/third-person singular present subjunctive
        third-person singular imperative
```

It's because of this formatting. `form-of` requires that it's accompanied by certain keywords and an of, so "second-person singular present indicative of amare" qualifies, but "inflection of amare:... second-person singular present indicative" doesn't. I'll take a look at it next week more in-depth, unless it turns out to be trivial.

**Comment by kristian-clausal** [comment] 2024-02-23 11:18
I've committed a kludge (inserting it into a list of kludges) that specifically handles "inflection of" followed by a sublist of entries like these.

**Comment by Vuizur** [comment] 2024-02-23 13:08
I'll do it with the next released dump.  👍

**Comment by herschelrs** [comment] 2024-02-27 23:37
I've found quite a few of these, I'm specifically working with the Spanish dataset. These seem to happen with a handful of specific conjugations, and with some verbs with less common morphology (specifically reflexive verbs whose lemmas are recorded under the infinitive + reflexive pronoun, rather than as a sense under the infinitive generically). 

I found 18534 entries with `'args': {'1': 'es', '2': 'verb form'}` in a head_template but no sense with a form_of key.

**Comment by kristian-clausal** [comment] 2024-04-10 09:24
Kaikki has finally updated, and it seems like `form-of` is present now in at least 'impala' (Italian) and 'azure' (French).

This doesn't mean everything is now fixed, of course, but it will help to find the next issue.

**Comment by kristian-clausal** [comment] 2024-04-26 10:18
What does the situation look like, currently?

**Comment by Vuizur** [comment] 2024-04-30 12:59
The external hard drive I ran the calculations on seems to be dying, I will have to find another way to repeat it 😅.

**Comment by herschelrs** [comment] 2024-06-30 16:54
Finally reran my tests for Spanish: 18542 entries with `'args': {'1': 'es', '2': 'verb form'}` in a head_template but no sense with a form_of key, compared to 18534 last time. (These are probably new entries, rather than a regression?)

**Comment by kristian-clausal** [comment] 2024-07-01 04:50
Please give us some concrete example words to check out.

**Comment by herschelrs** [comment] 2024-07-01 13:51
Sure: "ababillares", "alumbramos", "cachamos", "descomiden", "apipa". (I
can get a longer list of course.)

The overwhelming majority of these have 'name': 'Spanish entries with
incorrect language header' in a category for their sense, though they all
seem well formed in the actual wikitext.

Some examples of those which are not verbs, of which there are <100:
"encantados", "jamases", "metadatos"

**Comment by xxyzz** [comment] 2024-07-02 02:25
I recently add some code for form-of templates in zh edition: #697, #695
It finds the text of `<i>` tag in the expanded template that has template name ends with `of`, maybe en edition could use the same strategy?

**Comment by kristian-clausal** [comment] 2024-07-02 05:08
Looking at cachamos, I... don't know why it's not parsing the tags. I'll take a look at it.

**Comment by kristian-clausal** [comment] 2024-07-02 06:34
Part of these are just that we don't handle unexpected "term/term" pairs, to which the fix is to add the data into tags.py, at least for cachamos. To fix these, we'd need to know what `term/term` pairs are found in these broken entries.

For `ababillares`, the template adds a novel `only used in te ababillares` text, probably introduced in 2022 in the new Module:es-inflections module. So it's just that moving target again. I might just remove it with a regex, should do the trick and the information provided is marginal.

**Comment by kristian-clausal** [comment] 2024-07-08 08:47
This seems to be working now, so closing the issue.

Some of the examples given are unparseable: "metadatos" does not have anything that could tell the parser that it's a plural of something (we need `plural of`), the gloss is just "metadata" in English. Likewise for `jamases`; the gloss is "Only used in jamás de los jamases", so there's no data there.

**Closed by kristian-clausal** 2024-07-08 08:47 UTC
