### ISSUE TITLE
Missing/incorrect conjugation tags for Czech verbs

### ISSUE THREAD

**Issue by 29jm** [tatuylonen/wiktextract#597] opened 2024-04-19 09:56 UTC
I have a small project that uses the JSON data for the Czech language at [1], and I've noticed a regression with verb forms, for most verbs. I'll use sledovat [2] as an example here. 

December 2023 dataset (correct):
![old_sledujme](https://github.com/tatuylonen/wiktextract/assets/6154077/411b1e7d-bcf1-4250-9b5f-4584ad9056c6)

April 2024 dataset (missing tags):
![new_sledujme](https://github.com/tatuylonen/wiktextract/assets/6154077/5aba8659-61ee-479e-863f-bfa9f15e51b4)

Some tags are also wrong, for instance this shouldn't be imperative but indicative:
![incorrect_tags](https://github.com/tatuylonen/wiktextract/assets/6154077/aee60652-5f33-4ad3-8048-024297682375)

I'm really grateful for the existence of this project, and I would have time to help fix this if needed :)

[1] https://kaikki.org/dictionary/Czech/index.html
[2] https://en.wiktionary.org/wiki/sledovat#Czech

**Comment by kristian-clausal** [comment] 2024-04-19 10:05
Yep, something is wrong all right. The template has been unchanged since spring last year, my browser history shows me that there was something about annoying with cs-conj-forms in 2022 (so not relevant, alas)... I can't remember touching code that would be super-relevant to this recently. I'll take a look at this next week.

**Comment by 29jm** [comment] 2024-04-19 10:19
Thank you for looking at this!

**Comment by kristian-clausal** [comment] 2024-04-22 11:56
The issue is our parser. Some changes to it causes the table parsing to break (when the context is a bit messy, I think, in this case having tables inside tables). I'll continue with this tomorrow.

**Comment by kristian-clausal** [comment] 2024-04-23 10:53
This should be fixed, keep your eyes peeled. If no new bugs appear due to this, kaikki should update by the day after tomorrow; maybe tomorrow if today's update catches this commit, otherwise it'll update with the old stuff and then start a new run with the changes tomorrow.

The issue was with making our tokenizing regex stricter; I (it was most probably me) added some carets to patterns meant to catch tokens that should appear only at the beginning of a *line*... However, our tokenizing process involves splitting up the lines into *strings*, and regex can't tell the difference between the start of a string and the start of... a string.

So when an italics or bold token (`''` and `'''`) appear in the line somewhere, where it is split (and handled with a simple state machine loop kind of thing), and the string after that contains ` !!`, it seems that `^ !` matches a pattern and eats it as the wrong `!` token instead of `!!`.

Ultimately I thought the best way to fix this was to use two variations of the regex, both generated from the same source, a list of strings containing the token patterns that are joined together, except the other TOKEN_RE pattern would not have the strings starting with `^` and would be used to match stuff in latter parts of a partitioned line.

**Comment by 29jm** [comment] 2024-04-23 15:00
Awesome! I'll make sure to check the new update

**Comment by kristian-clausal** [comment] 2024-04-24 04:40
The commit wasn't in time for last night's update, but it should be for the next one, so tomorrowish.

**Comment by kristian-clausal** [comment] 2024-04-26 10:17
Looking at sledujme in sledovat, looks better. I'll leave this open so you can point out if something is still broken.

**Comment by 29jm** [comment] 2024-04-26 10:46
Yeah it looks very much fixed, I'm seeing similar amounts of good verb forms as before now. Thank you. I think this can be safely closed.

**Closed** 2024-04-26 10:47 UTC
